local M = {}

function M.get_commands()
    return {
        {
            label = "Remove Comments",
            locations = {"Edit", "Assets"},
            query = {
                selection = {type = "resource", cardinality = "one"}
            },
            active = function(opts)
                local path = editor.get(opts.selection, "path")
                return ends_with(path, ".lua") or ends_with(path, ".script")
            end,
            run = function(opts)
                local text = editor.get(opts.selection, "text")
                return {
                    {
                        action = "set",
                        node_id = opts.selection,
                        property = "text",
                        value = strip_comments(text)
                    }
                }
            end
        },
        {
            label = "Minify JSON"
            locations = {"Assets"},
            query = {
                selection = {type = "resource", cardinality = "one"}
            },
            active = function(opts)
                return ends_with(editor.get(opts.selection, "path"), ".json")
            end,
            run = function(opts)
                local path = editor.get(opts.selection, "path")
                return {
                    {
                        action = "shell",
                        command = {"./scripts/minify-json.sh", path:sub(2)}
                    }
                }
            end
        }
    }
end

return M